default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: u0157585


development:
  <<: *default
  database: doorbell_development
  host: localhost

test:
  <<: *default
  database: doorbell_test
  host: localhost

production:
  <<: *default
  database: doorbell_production
  password: <%= ENV['DOORBELL_DATABASE_PASSWORD'] %>
